create table public.rate_limit_events (
  id bigint generated by default as identity primary key,
  key_hash text not null,
  action text not null,
  created_at timestamptz not null default now()
);
create index rate_limit_events_lookup_idx on public.rate_limit_events(key_hash, action, created_at desc);
alter table public.rate_limit_events enable row level security;
