alter table public.messages add column if not exists risk_score integer not null default 0;
alter table public.reports add column if not exists risk_score integer not null default 0;
create table if not exists public.security_events (
 id bigint generated by default as identity primary key,
 event_type text not null,
 subject_hash text,
 created_at timestamptz not null default now()
);
create index if not exists security_events_type_time_idx on public.security_events(event_type,created_at desc);
alter table public.security_events enable row level security;
